swagger: "2.0"
info:
  title: 区块链存证系统服务调用 API
  description: 区块链存证系统服务调用 API
  version: 1.0.0
  termsOfService: https://mikeygithub.github.io/
  contact:
    email: biaogejiushibiao@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /api
paths:
  /fabric/save:
    post:
      tags:
      - fabric
      description: Save FabricFile to BlockChain
      operationId: FabricFileController.Save
      parameters:
      - in: body
        name: body
        description: body for FabricFile content
        required: true
        schema:
          $ref: '#/definitions/models.FabricFile'
      responses:
        "201":
          description: '{int} models.FabricFile'
        "403":
          description: body is empty
  /fabric/verify:
    post:
      tags:
      - fabric
      description: verify FabricFile from BlockChain by hashcode
      operationId: FabricFileController.Verify
      parameters:
      - in: body
        name: body
        description: body for FabricFile content
        required: true
        schema:
          $ref: '#/definitions/models.FabricFile'
      responses:
        "201":
          description: '{int} models.FabricFile'
        "403":
          description: body is empty
definitions:
  models.FabricFile:
    title: FabricFile
    type: object
tags:
- name: fabric
  description: |
    FabricFileController operations for FabricFile
